// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package api

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CheckHealth provides a mock function with given fields: ctx
func (_m *MockService) CheckHealth(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_CheckHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckHealth'
type MockService_CheckHealth_Call struct {
	*mock.Call
}

// CheckHealth is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) CheckHealth(ctx interface{}) *MockService_CheckHealth_Call {
	return &MockService_CheckHealth_Call{Call: _e.mock.On("CheckHealth", ctx)}
}

func (_c *MockService_CheckHealth_Call) Run(run func(ctx context.Context)) *MockService_CheckHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_CheckHealth_Call) Return(_a0 error) *MockService_CheckHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_CheckHealth_Call) RunAndReturn(run func(context.Context) error) *MockService_CheckHealth_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
