// Code generated by mockery. DO NOT EDIT.

//go:build !compile

package user

import (
	context "context"

	redis "github.com/redis/go-redis/v9"
	mock "github.com/stretchr/testify/mock"
)

// MockuserDAO is an autogenerated mock type for the userDAO type
type MockuserDAO struct {
	mock.Mock
}

type MockuserDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockuserDAO) EXPECT() *MockuserDAO_Expecter {
	return &MockuserDAO_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *MockuserDAO) Ping(ctx context.Context) *redis.StatusCmd {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *redis.StatusCmd
	if rf, ok := ret.Get(0).(func(context.Context) *redis.StatusCmd); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}

	return r0
}

// MockuserDAO_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockuserDAO_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockuserDAO_Expecter) Ping(ctx interface{}) *MockuserDAO_Ping_Call {
	return &MockuserDAO_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockuserDAO_Ping_Call) Run(run func(ctx context.Context)) *MockuserDAO_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockuserDAO_Ping_Call) Return(_a0 *redis.StatusCmd) *MockuserDAO_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockuserDAO_Ping_Call) RunAndReturn(run func(context.Context) *redis.StatusCmd) *MockuserDAO_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockuserDAO creates a new instance of MockuserDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockuserDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockuserDAO {
	mock := &MockuserDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
